version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    hostname: 0.0.0.0
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    command: >
      sh -c "sleep 10 && alembic upgrade head && python prescript.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}

    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

# Определение тома для постоянных данных PostgreSQL
# volumes:
#   postgres_data:
#     driver: local