"""Initial revision

Revision ID: 22772d584ee2
Revises: 
Create Date: 2025-02-18 15:32:45.840623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22772d584ee2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('conference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'presentations', 'conferences', ['conference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presentations', type_='foreignkey')
    op.drop_column('presentations', 'conference_id')
    # ### end Alembic commands ###
