"""added column description to presentation table

Revision ID: 274499b1f355
Revises: c2940a1910e7
Create Date: 2025-03-05 23:00:52.999102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274499b1f355'
down_revision: Union[str, None] = 'c2940a1910e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'description')
    # ### end Alembic commands ###
