"""added indexes

Revision ID: c2940a1910e7
Revises: d2c9ef32f383
Create Date: 2025-03-05 22:13:01.771777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2940a1910e7'
down_revision: Union[str, None] = 'd2c9ef32f383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conferences_name'), 'conferences', ['name'], unique=False)
    op.drop_constraint('presentations_name_key', 'presentations', type_='unique')
    op.create_index(op.f('ix_presentations_name'), 'presentations', ['name'], unique=True)
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.create_index('ix_users_first_name_last_email', 'users', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index('ix_users_first_name_last_email', table_name='users')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.drop_index(op.f('ix_presentations_name'), table_name='presentations')
    op.create_unique_constraint('presentations_name_key', 'presentations', ['name'])
    op.drop_index(op.f('ix_conferences_name'), table_name='conferences')
    # ### end Alembic commands ###
